### ISSUE TITLE
Capacitor 6 support för Android

### ISSUE THREAD

**Issue by daevid66** [CraigRonald555/capacitor-subscriptions#21]
I have a version of my app working with the subscriptions plugin on ios but when I upload to Google Play Store I get warnings that I need to target sdk version 34. 

It looks like Capacitor 6 is targeting sdk 34 so I tried to migrate. After doing this I get the following error:

NativePlugin com.capicitor_subscriptions.capacitor.SubscriptionsPlugin failed to load
com.getcapacitor.PluginLoadException: Unable to load plugin instance. Ensure plugin is publicly accessible

Is there something that needs to be done to make the plugin work with capacitor 6?

**Comment by nesha14586** [comment]
@daevid66 There's an open PR (from April 2024.) with this feature, for supporting capacitor 6, I don't know why it wasn't merged yet: https://github.com/Craig-Ronald/capacitor-subscriptions/pull/13

Maybe @CraigRonald555 can give more info.

**Comment by CraigRonald555** [comment]
Apologies, the Capacitor 6 version has not been fully tested on Android hence why the pull request has remained open until I find time to test on a real device.

@daevid66 Are you running the 1.0.3-alpha version? This should work with Capacitor 6, but if it doesn't then I can fix it over the weekend.

**Comment by daevid66** [comment]
Thank you for your answer, I will try out the alpha version and let you know the results!

**Comment by daevid66** [comment]
It looks like I'm getting the same error, unfortunately. 

Right after the log: "Registering plugin instance: Subscriptions", I get the error:
NativePlugin com.capicitor_subscriptions.capacitor.SubscriptionsPlugin failed to load
com.getcapacitor.PluginLoadException: Unable to load plugin instance. Ensure plugin is publicly accessible
at com.getcapacitor.PluginHandle.load(PluginHandle.java:107)

I'm running in Android Studio Emulator (Medium Phone API 35)

**Comment by CraigRonald555** [comment]
> It looks like I'm getting the same error, unfortunately.
> 
> Right after the log: "Registering plugin instance: Subscriptions", I get the error: NativePlugin com.capicitor_subscriptions.capacitor.SubscriptionsPlugin failed to load com.getcapacitor.PluginLoadException: Unable to load plugin instance. Ensure plugin is publicly accessible at com.getcapacitor.PluginHandle.load(PluginHandle.java:107)
> 
> I'm running in Android Studio Emulator (Medium Phone API 35)

I’ll do some development and testing over the weekend, and should have a new version out by Sunday. 

In the meantime, I’d recommend retrying with a real device (if you have access to one). I believe Google Billing can be temperamental when using emulators.

**Comment by josuelmm** [comment]
Any update?

**Comment by riderx** [comment]
use https://github.com/Cap-go/capacitor-native-purchases it's working in v6 and v7
